### ISSUE TITLE
Release for NPM

### ISSUE THREAD

**Issue by GaborTorma** [kalmecak/moment-business-days#99]
Please create a new release for NPM with forcedBusinessDays support.
NPM has an old, 2 years version.
Thanx!

**Comment by GaborTorma** [comment]
Please create a new release.

**Comment by mcdado** [comment]
@kalmecak if you want I can help you setup GitHub Actions so that when we create a release on here, a new release is published to npm. I've had some experience in this regard so it wouldn't require you much ongoing work if at all.

**Comment by kalmecak** [comment]
It would be nice, how can we do that?

**Comment by mcdado** [comment]
There's an official guide on GitHub: [Publishing Node.js packages](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages)

I did it for another package that I publish, first you need to add a NPM Token as a **Repository secret** in the **Repository Settings**:  
<img width="1117" alt="Screenshot 2021-11-22 at 11 03 52" src="https://user-images.githubusercontent.com/898057/142841856-c88d7d26-1e92-4fb6-9964-c34d334056b5.png">


Then add an action file. Here's the one from another project of mine:  
https://github.com/mcdado/node-helpscout/blob/3ca7f5148428208a2212c25cbea63563142008d6/.github/workflows/publish_on_release.yml

```yml
name: publish node package to npm
on:
  release:
    types: [created]
jobs:
  publish_to_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

When you create a release it will automatically publish a new version to NPM. You have to make sure to bump the version in `package.json`.
